create database banksystem;

CREATE TABLE Account(CNumber INT NOT NULL PRIMARY KEY IDENTITY(1000,1), CName VARCHAR(50) NOT NULL, CPhone VARCHAR(50) NOT NULL, CAddress VARCHAR(100) NOT NULL, CPass VARCHAR(50) NOT NULL, CBal INT NOT NULL);

CREATE TABLE TransferTbl( TrID INT NOT NULL PRIMARY KEY IDENTITY, TrSrc INT NOT NULL, TrDest INT NOT NULL, TrAmt INT NOT NULL, TrDate DATE NOT NULL);

