name: Code coverage artifact

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build
      run: dotnet build --no-restore 

    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage 

    - name: Code Coverage Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Code Coverage Report - XMl
      run: reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverlet/reports -reporttypes:"Cobertura"

    - name: Code Coverage Report - HTML
      run: reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverlet/reports -reporttypes:Html

    - name: Upload Artefacts
#      run: mkdir -p $GITHUB_WORKSPACE/coverage/

      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverlet/reports
