name: code_coverage

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
        
    - name: Restore Dependencies
      run: dotnet restore banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj

    - name: Build
      run: dotnet build banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj
      
    - name: Run tests with code coverage
      run: dotnet test  --no-build banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj --collect:"XPlat Code Coverage" --results-directory ./coverage
   
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
          name: code-coverage-report
          path: coverage/**/coverage.cobertura.xml
