name: code_coverage

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
        
    - name: Restore Dependencies
      run: dotnet restore banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj

    - name: Build
      run: dotnet build banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj
      
    - name: Run tests with code coverage
      run: dotnet test  banksystem/BankApplication/BankApplicationTest/BankApplicationTest.csproj --collect:"XPlat Code Coverage"

    - name: Install reportgenrator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Cobertura report
      run: reportgenerator -reports:coverage.cobertura.xml -targetdir:coverlet/reports -reporttypes:"Cobertura"

    - name: HTML report
      run: reportgenerator -reports:coverage.cobertura.xml -targetdir:coverlet/reports -reporttypes:HtmlInline_AzurePipelines
   
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
          name: code-coverage-report
          path: output/test/code-coverage.html
