# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore Dependencies
      run: dotnet restore banksystem/BankApplication/BankApplication/BankApplication.csproj
      
    - name: Build
      run: dotnet build banksystem/BankApplication/BankApplication/BankApplication.csproj
      
  test:
    needs: build
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    
    steps:
     - uses: actions/checkout@v4
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
     - name: Restore Dependencies
       run: dotnet restore banksystem/BankApplication/BankApplication/BankApplication.csproj
        
     - name: Test
       run: dotnet test banksystem/BankApplication/BankApplication/BankApplication.csproj

  lint: 
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Super-Linter
        uses: super-linter/super-linter@v5.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lint_file: '.github/linters/.super-linter.yml'
          working_path: './'

      - name: Run Super-Linter
        run: ./entrypoint.sh
          
        
            
  
  
