# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore Dependencies
      run: dotnet restore banksystem/BankApplication/BankApplication/BankApplication.csproj
      
    - name: Build
      run: dotnet build banksystem/BankApplication/BankApplication/BankApplication.csproj
      
  test:
    needs: build
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    
    steps:
     - uses: actions/checkout@v4
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
     - name: Restore Dependencies
       run: dotnet restore banksystem/BankApplication/BankApplication/BankApplication.csproj
        
     - name: Test
       run: dotnet test banksystem/BankApplication/BankApplication/BankApplication.csproj

  super-lint:
     name: Lint code base
     runs-on: windows-latest
     steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Super-Linter
          uses: github/super-linter@v4
          env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
        
            
  
  
