name: lint

on: 
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   build:
     runs-on: ubuntu-latest
     
     steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
             dotnet-version: '6.0.x'
             
        - name: Install dependencies
          run: dotnet restore banksystem/BankApplication/BankApplication/BankApplication.csproj

        - name: Run linting
          run: dotnet build /p:RunAnalyzersDuringBuild=true

